[package]
name = "mtdparts"
version = "0.1.1"
authors = ["Arvid E. Picciani <aep@exys.org>"]
description = "parses /proc/mtd"
repository = "https://github.com/aep/mtdparts"
license = "MIT"

[dependencies]
regex = "0.2"
failure = "0.1"
